export enum ConfigKeys {
  PORT = 'PORT',
  POSTGRES_HOST = 'HOST',
  POSTGRES_USERNAME = 'POSTGRES_USERNAME',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_DATABASE = 'POSTGRES_DATABASE',
  JWT_SECRET = 'JWT_SECRET',
  POSTGRES_CONNECTION = 'POSTGRES_CONNECTION',
  TYPEORM_SYNC = 'TYPEORM_SYNC',
  NODE_ENV = 'NODE_ENV',
}
